 * Serving Flask app 'main'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 626-793-910
 * Serving Flask app 'main'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 626-793-910
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 626-793-910
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 7, in <module>
    from config.Variables.variables import *
  File "/home/raphael/Bureau/Programmation/Python/Onche/config/Variables/variables.py", line 9, in <module>
    MYSQL_BOT_BLABLA = BOT_blabla
                       ^^^^^^^^^^
NameError: name 'BOT_blabla' is not defined
 * Serving Flask app 'main'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Serving Flask app 'main'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Serving Flask app 'main'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
127.0.0.1 - - [20/Jan/2024 19:11:31] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 19:12:28] "[33mGET / HTTP/1.1[0m" 404 -
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/mysql/connector/plugins/__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/mysql/connector/version.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/config/Variables/variables.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
127.0.0.1 - - [20/Jan/2024 19:20:20] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 19:20:21] "[35m[1mGET /api/babelonche/general/info HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 74, in get_info
    data = get_database_version()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py", line 10, in get_database_version
    bdd = DDB.split("_")[1]
          ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
 * Serving Flask app 'main'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
127.0.0.1 - - [20/Jan/2024 19:20:53] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 19:20:53] "[35m[1mGET /api/babelonche/general/info HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 74, in get_info
    data = get_database_version()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py", line 10, in get_database_version
    bdd = DDB.split("_")[1]
          ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
 * Serving Flask app 'main'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
127.0.0.1 - - [20/Jan/2024 19:21:58] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 19:21:58] "[35m[1mGET /api/babelonche/general/info HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 74, in get_info
    data = get_database_version()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py", line 10, in get_database_version
    bdd = DDB.split("_")[1]
          ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
 * Serving Flask app 'main'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
127.0.0.1 - - [20/Jan/2024 19:51:40] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 19:51:41] "[35m[1mGET /api/babelonche/general/info HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 88, in get_info
    data = get_database_version()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py", line 10, in get_database_version
    bdd = DDB.split("_")[1]
          ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py', reloading
 * Restarting with stat
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 105
    r = 
        ^
SyntaxError: invalid syntax
 * Serving Flask app 'main'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
127.0.0.1 - - [20/Jan/2024 21:05:46] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:05:46] "[35m[1mGET /api/babelonche/general/info HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 75, in get_info
    data = get_database_version()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py", line 10, in get_database_version
    bdd = DDB.split("_")[1]
          ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Serving Flask app 'main'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
127.0.0.1 - - [20/Jan/2024 21:10:24] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:10:24] "[35m[1mGET /api/babelonche/general/info HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 86, in get_info
    data = get_database_version()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py", line 10, in get_database_version
    bdd = DDB.split("_")[1]
          ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
127.0.0.1 - - [20/Jan/2024 21:10:27] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:10:28] "[35m[1mGET /api/babelonche/general/info HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 86, in get_info
    data = get_database_version()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py", line 10, in get_database_version
    bdd = DDB.split("_")[1]
          ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
127.0.0.1 - - [20/Jan/2024 21:10:38] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:10:39] "GET /api/babelonche/mysql/state HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2024 21:10:39] "GET /api/babelonche/mysql/info HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2024 21:10:41] "GET /api/babelonche/database/info HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2024 21:10:41] "[35m[1mGET /api/babelonche/general/info HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 86, in get_info
    data = get_database_version()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py", line 10, in get_database_version
    bdd = DDB.split("_")[1]
          ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
127.0.0.1 - - [20/Jan/2024 21:10:45] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:10:45] "[35m[1mGET /api/babelonche/general/info HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 86, in get_info
    data = get_database_version()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py", line 10, in get_database_version
    bdd = DDB.split("_")[1]
          ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
127.0.0.1 - - [20/Jan/2024 21:12:12] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:12:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:12:20] "[33mGET /api/babelonche/database/import/BDD_import/sql HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:12:22] "[33mGET /api/babelonche/database/import/BDD_import/sql HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:12:32] "[33mGET /api/babelonche/database/import/ HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:12:32] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:12:34] "GET /api/babelonche/database/import HTTP/1.1" 200 -
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/database/mysql.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
127.0.0.1 - - [20/Jan/2024 21:13:31] "[33mGET /api/babelonche/database/import/Onche HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:13:35] "[33mGET /api/babelonche/database/import/ HTTP/1.1[0m" 404 -
127.0.0.1 - - [20/Jan/2024 21:13:37] "GET /api/babelonche/database/import HTTP/1.1" 200 -
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
127.0.0.1 - - [20/Jan/2024 21:13:48] "GET /api/babelonche/database/import HTTP/1.1" 200 -
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/database/mysql.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/database/mysql.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/database/mysql.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/database/mysql.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/database/mysql.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/utils/general.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 467-723-749
 * Detected change in '/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py", line 571, in __init__
    self.connexion = connect_local(database=self.database)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/main.py", line 8, in <module>
    from WebAPP.API.function.database.mysql import *
  File "/home/raphael/Bureau/Programmation/Python/Onche/WebAPP/API/function/database/mysql.py", line 7, in <module>
    from BDD.bdd import BDD
  File "/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py", line 578, in <module>
    bdd = LocalBDD()
          ^^^^^^^^^^
  File "/home/raphael/Bureau/Programmation/Python/Onche/BDD/bdd.py", line 575, in __init__
    raise Exception(f"Echec de la connexion à la base de donnée : {e}")
Exception: Echec de la connexion à la base de donnée : unable to open database file
 * Serving Flask app 'main'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 279-331-283
127.0.0.1 - - [29/Jan/2024 21:37:31] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [29/Jan/2024 21:37:31] "GET /api/babelonche/mysql/state HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2024 21:37:31] "GET /api/babelonche/mysql/info HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2024 21:37:33] "GET /api/babelonche/database/info HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2024 21:37:34] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [29/Jan/2024 21:37:34] "GET /api/babelonche/mysql/state HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2024 21:37:34] "GET /api/babelonche/mysql/info HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2024 21:37:35] "GET /api/babelonche/database/info HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2024 21:37:35] "GET /api/babelonche/general/info HTTP/1.1" 200 -
